os: osx
language: swift
osx_image: xcode10.2.1

branches:
  only:
    - master

script:
  - xcodebuild clean build test -project SwiftIcons.xcodeproj -scheme SwiftIcons -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0.1' CODE_SIGNING_REQUIRED=NO | xcpretty

notifications:
  email:
    on_success: never
    on_failure: change
